server:
  port: 8081

spring:
  data:
    redis:
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:db/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    hikari:
      schema: bank_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS bank_schema
      connection-timeout: 10000

  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

user-service:
  jwt:
    secret: ${SECRET_KEY}
    tokenExpiration: 10m
    refreshTokenExpiration: 60m

encryption:
  secret: ${ENCRYPTION_SECRET}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  packages-to-scan: com.github.seecret1.bank_card_management_system.controller
  paths-to-match: /api/v1/**